import { chromium } from "playwright";
import { enterWorld } from "./lib/enter.mjs";
import fs from "node:fs";
const gpu = process.env.GPU === "1";
const browser = await chromium.launch({ headless: !gpu, channel: gpu ? "chrome" : undefined, args: gpu ? [] : ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1" });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto((process.env.ARCHON_BASE ?? "http://localhost:3210") + "/en", { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
fs.mkdirSync(".qa/world", { recursive: true });
console.log("overlay text:", (await page.locator(".world-overlay").innerText().catch(() => "")).replace(/\s+/g, " ").slice(0, 300));
await enterWorld(page, process.env.LANG_WORLD || "tr", 3500);
await page.screenshot({ path: ".qa/world/tour-m-1.png" });
await page.waitForTimeout(6000);
await page.screenshot({ path: ".qa/world/tour-m-2.png" });
const hud = await page.locator(".world-overlay").innerText().catch(() => "");
console.log("hud:", hud.replace(/\s+/g, " ").slice(0, 400));
const info = await page.evaluate(() => (window.__archonInfo ? window.__archonInfo() : null));
console.log("info:", JSON.stringify(info));
console.log("errors:", errors);
await browser.close();
