/** The world's language: Turkish by default, English on request, remembered, switchable in the HUD. */
import { chromium } from "playwright";
import { enterWorld } from "./lib/enter.mjs";
const BASE = "http://localhost:3210";
let passed = 0, failed = 0;
const check = (name, ok, note = "") => { console.log(`${ok ? "PASS" : "FAIL"}  ${name}${note ? `  — ${note}` : ""}`); ok ? passed++ : failed++; };
const browser = await chromium.launch({ args: ["--enable-unsafe-swiftshader", "--use-gl=angle", "--use-angle=swiftshader"] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto(`${BASE}/en`, { waitUntil: "networkidle" });
const overlay = page.locator(".world-overlay");
await page.locator("[data-enter]").waitFor({ state: "visible", timeout: 60000 });
await page.waitForTimeout(1300);
check("on the English site the world still opens in Turkish", /B[İi]R D[İi]L SEÇ[İi]N|Bir dil seçin/i.test(await overlay.innerText()));
check("Turkish is the selected language", (await page.locator('.world-overlay [data-lang="tr"][aria-checked="true"]').count()) === 1);
await page.locator('.world-overlay [data-lang="en"]').click();
await page.locator("[data-enter]").click();
await page.waitForTimeout(6000);
let hud = await overlay.innerText();
check("after choosing English the HUD is English", /MOVE/.test(hud) && /FOUND/.test(hud) && !/BULUNDU/.test(hud), hud.replace(/\s+/g, " ").slice(-160));
await page.locator('.world-overlay [data-lang="tr"]').last().click();
await page.waitForTimeout(600);
hud = await overlay.innerText();
check("switching to TR in the HUD changes the world without a reload", /YÜRÜ/.test(hud) && /BULUNDU/.test(hud) && !/FOUND\b/.test(hud), hud.replace(/\s+/g, " ").slice(-160));
check("the language is remembered", (await page.evaluate(() => localStorage.getItem("archon-world-lang"))) === "tr");
/* A guide, in Turkish: the tour list is not here on desktop, so speak to one through the payload hook: walk is slow on software; use the interactable directly. */
await page.locator('.world-overlay [data-lang="en"]').last().click();
await page.waitForTimeout(400);
check("the language is remembered again", (await page.evaluate(() => localStorage.getItem("archon-world-lang"))) === "en");
await page.reload({ waitUntil: "networkidle" });
await page.locator("[data-enter]").waitFor({ state: "visible", timeout: 60000 });
await page.waitForTimeout(1300);
check("the next visit opens in the remembered language", (await page.locator('.world-overlay [data-lang="en"][aria-checked="true"]').count()) === 1 && /Enter the world/i.test(await page.locator("[data-enter]").innerText()));
check("no page errors", errors.length === 0, errors.join(" | ").slice(0, 200));
await browser.close();
console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
